# Generated by Django 3.1.6 on 2021-06-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('nameoncard', models.CharField(max_length=50)),
                ('creditcardnumber', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('cvv', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
