# Generated by Django 3.1.6 on 2021-07-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='image',
            field=models.ImageField(default=0, upload_to='select'),
            preserve_default=False,
        ),
    ]
