# Generated by Django 3.1.6 on 2021-07-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_payment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='image',
        ),
        migrations.AddField(
            model_name='payment',
            name='productname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
